DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS songs CASCADE;

CREATE TABLE users(
    userId VARCHAR(50) NOT NULL PRIMARY KEY,
    key VARCHAR(50) NOT NULL ,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL);

CREATE TABLE songs(
    id SERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(50) NOT NULL,
    artist VARCHAR(50) NOT NULL,
    label VARCHAR(50) NOT NULL,
    released INTEGER NOT NULL);